apiVersion: v1
kind: Service
metadata:
  name: blerter-db
spec:
  type: NodePort
  ports:
  - name: pgql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: blerter-db
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blerter-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: blerter-db
        app: blerter-db
    spec:
      containers:
        - name: blerter-db
          image: sirwhitemonkey/blerter-db
          #resources:
          #  requests:
          #    memory: 256Mi
          #  limits:
          #    memory: 256Mi  
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-pv-claim
      volumes:
        - name: postgres-pv-claim
          persistentVolumeClaim:
            claimName: postgres-pv-claim